# Generated by Django 3.1.5 on 2021-09-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_commentmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelTable(
            name='commentmodel',
            table='comment',
        ),
    ]
